abstract class MainPropertyState{}
class MainPropertyInitialState extends MainPropertyState{}
class MainPropertyCurrentLocationPickingLoadingState extends MainPropertyState{}
class MainPropertyCurrentLocationPickedState extends MainPropertyState{}
class MainPropertylocationFixedState extends MainPropertyState{}
// class MainPropertyImageSelectedState extends MainPropertyState{}
class MainPropertyLoadingState extends MainPropertyState{}
class MainPropertyUpdatedState extends MainPropertyState{}